### ISSUE TITLE
Broken Makefile

### ISSUE THREAD

**Issue by radare** [leberus/r2k#2]
* Doesn't works in x86 (copied the makefile from c0412388213baa437eb7d7cf9a97f4683bfc4027)
* Missing install/uninstall targets

**Comment by leberus** [comment]
should be fixed by commit above

**Comment by leberus** [comment]
I think this could be closed too. Could you confirm? thanks

**Comment by radare** [comment]
you can confirm with r2pm -i r2k-linux-unstable

i dont have a linux machine handy right now

**Comment by leberus** [comment]
is working :D, i'm closing this issue
