### ISSUE TITLE
=!M not working on x86

### ISSUE THREAD

**Issue by radare** [leberus/r2k#5]
Better show a meaningful error like `not implemented, or not supported` than `ioctl err: Operation not permitted`

**Comment by leberus** [comment]
I've changed the return value for not implemented features. Returning ENOSYS (function not implemented) should be more than enough.
panda has added the chack on userland and it's working.
[commit](https://github.com/leberus/r2k/commit/2ac3b19f8ab0580b73d75701b94eb5c126a2fc6d)
