### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by radare** [leberus/r2k#7]
the r2k module doesn't checks for userid or group or anything. This allows anyone to read or write the entire system memory without any kind of protection.

i would go for adding a compile time option enabled by default to check if user opening the device is UID=0

**Comment by jpenalbae** [comment]
I would not like to have to run r2 under uid 0 every time... I think that creating the device with root:root and 600 permissions by default should be enough.

**Comment by radare** [comment]
Then what about honoring file permissions of the /dev/r2k device? Because i can write memory even if i have only read permissions for the user

**Comment by jpenalbae** [comment]
Permissions are not implement by the module, but by the VFS. Memory read/write operations are implemented through ioctls, and having read permissions to read the device is enough to issue ioctls.

I would suggest to create the r2k device  with  600 perms by default, cause even if we block access to the write ioctl, reading kernel memory is still a big security issue. Later if a user wants to access r2k without being root, its his/her responsibility to change the device permissions.

Anyway.... lets face the facts, this module by itself its a security risk. Even restricting it to root, this should never be installed onto a "real" machine.

**Comment by radare** [comment]
Yep but this should be notified to the user somehow if we dont wanna appear in the news

**Comment by jpenalbae** [comment]
Maybe we should printk() a warning message every time the module is loaded...

**Comment by leberus** [comment]
I've changed the code, so now the device is created with 0600 by default, and only root user can talk to dev. (user can change that whenever he wants). [commit](https://github.com/leberus/r2k/commit/303dc8eabca288dceca3af04d603d4d169de71b0)
Any suggestion about which message should we print?

**Comment by jpenalbae** [comment]
Probably something like: "WARNING: This module implies a security risk as it allows direct read/write to the system memory. Use it only under test systems at your own risk"

**Comment by leberus** [comment]
I think this would make the trick: [commit](https://github.com/leberus/r2k/commit/82525aa58d5049b1bbb4b4324fbe10aceb38968e)

I'll close this issue if everybody is happy with that

**Comment by radare** [comment]
Looks good to me
